### ISSUE TITLE
Add ability for user to update email and password in frontend

### ISSUE THREAD

**Issue by UFdylantosh** [cwojtak/GatorSecurity#43]

**Comment by UFdylantosh** [comment]
Task: Create a new page, form, and button for a user to be able to alter one's email address or password.

**Comment by kerryhannigan** [comment]
I was going to work on this but then noticed that my first/last name aren't populated on the edit profile page. are you still doing other work on that page? @UFdylantosh

**Comment by UFdylantosh** [comment]
Not currently. I fixed a bug though causing that issue. Should be functional now.

**Comment by cwojtak** [comment]
@kerryhannigan
I don't think the latest pull request actually changes a user's email (I think the line that does that is commented out?).
Also, I think we have to implement a check to make sure a user doesn't change their email to an existing email address.
One last thing too is that, on the front end, I think the user needs to be logged out so they can regenerate their token with any new email address.

**Comment by kerryhannigan** [comment]
@cwojtak also for the future, comments like these can be left in the PR and you can comment on a specific line to make it clear what you're referring to.

**Comment by kerryhannigan** [comment]
One more note: you can always pull a branch down and test it yourself if you're not sure whether it works. We could even make it a standard for approving, if we want to

**Comment by cwojtak** [comment]
Ah i didn't know that; sorry
