### ISSUE TITLE
Figure out what to do with game questions 2 and 3

### ISSUE THREAD

**Issue by cwojtak** [cwojtak/GatorSecurity#69]

**Comment by cwojtak** [comment]
We can either leave these on the game page or maybe we can turn them into choose your own questions

2 can't be made into a traditional question as it displays a special table
3 can't be made into a traditional question as it has two entry boxes

**Comment by kerryhannigan** [comment]
Looking at the if/else blocks for questions 2 or 3, I still think they each have just one answer that can be put in the database. There are other UI elements involved but as long as the questions and answers are 1:1, there should be no issue migrating them.

**Comment by kerryhannigan** [comment]
Question 2 just displays the table after you put in the correct answer, and question 3 only checks the email input for the correct answer.
