### ISSUE TITLE
Bug - learn score is not actually updated

### ISSUE THREAD

**Issue by kerryhannigan** [cwojtak/GatorSecurity#80]
![image](https://user-images.githubusercontent.com/24442475/218181176-64808285-2a11-411f-aeef-8008d567dfa2.png)

![image](https://user-images.githubusercontent.com/24442475/218180616-c31f9212-59f2-44cc-8921-d95b392742ac.png)

**Comment by cwojtak** [comment]
When I tested it last it seemed to be working
If it's not working for you, you might need to create a new user as the schema was changed

**Comment by kerryhannigan** [comment]
Idk how it could work... it's taking the array from the db, putting it in a temp variable, then passing that temp variable back into the db.. I could be missing something too though

**Comment by cwojtak** [comment]
I mean it's just grabbing the old scores and putting it in a map, adding a new score to the map, and then saving that map to the database? The updateOne function copies the map, so it's not like the map given to the database is falling out of scope or something.

**Comment by kerryhannigan** [comment]
ohhhh I didn't see line 171

**Comment by kerryhannigan** [comment]
actually @cwojtak it's still not working for me even on main, without my changes.

**Comment by cwojtak** [comment]
Ah yeah you'll need to make a new user then
